export const GENERATE_PAYSLIP = 'GENERATE_PAYSLIP';
export const ADD_LOGIN_CREDENTIALS = 'ADD_LOGIN_CREDENTIALS';
export const ADD_STATUS_OF_CREATED_PAYSLIP = 'ADD_STATUS_OF_CREATED_PAYSLIP';
export const ADD_PREV_PAYSLIPS = 'ADD_PREV_PAYSLIPS';
